@bugdgetwarsapi_HostAddress = http://localhost:5000

GET {{bugdgetwarsapi_HostAddress}}/weatherforecast/
Accept: application/json

#####


### Create Expense
POST {{bugdgetwarsapi_HostAddress}}/api/expense
Content-Type: application/json
Accept: application/json

